### PR TITLE
Quality of life updates for Cocoapods >= 1.13.0. Resolves #12

### LINKED ISSUE #12: Gem::ConflictError with new released cocoapods-downloader-2.0
Hi,

since last week everything was working fine, but unfortunately on 2023-10-26 cocoapods-downloader was released in version 2.0, see https://rubygems.org/gems/cocoapods-downloader/versions/2.0

Since then I get this error when running pod install:
`Gem::ConflictError - Unable to activate cocoapods-azure-universal-packages-0.1.0, because cocoapods-downloader-2.0 conflicts with cocoapods-downloader (~> 1.0)`

I guess in https://github.com/microsoft/cocoapods-azure-universal-packages/blob/main/cocoapods-azure-universal-packages.gemspec the runtime version dependency to cocoapods-downloader should be updated to 2.0 to stay compatible!?

Please can you try to have a look and fix it?

Thanks
Ben

### PR DESCRIPTION
**Pull request by mitchins**
The plugin as-is will not work with cocoapods 0.13.0 or higher due to changes in the Cocoapods downloader as described in #12 

It is only required to bump some dependencies and the assembled gem works perfectly when tested locally.
Given nothing else has changed, it is logical to version it as 0.1.1

Tested on Cocoapods 1.15.0

### CODE REVIEW

**Comment by mitchins** [comment]
@microsoft-github-policy-service agree [company="private account"]

**Comment by mitchins** [comment]
@microsoft-github-policy-service agree

**Comment by rbviz** [comment]
I've forked and published [cocoapods-azure-universal-packages2](https://github.com/rbviz/cocoapods-azure-universal-packages2)

It's baffling how Microsoft mistreats this gem. Good luck.

**Review by tehmur — APPROVED** [review]

**Comment by mitchins** [comment]
@tehmur  thanks for approving it.
Please approve the workflow if possible to re-run the tests.

As I wasn't able to run the tests until now - or even locally (I don't have actions installed locally) I have updated the YAML for the tests, as it seems the previous entry of ruby 2.6 is too old, I have simply changed it to 2.7 as indicated and hope this will be fine.

**Comment by rbviz** [comment]
2.7 is already obsolete. 3.0 is approaching EOL. 

Check this https://www.ruby-lang.org/en/downloads/branches/

**Review by tehmur — APPROVED** [review]

**Pull request merged**
